# Generated by Django 3.2.4 on 2021-08-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default=None, max_length=10)),
                ('event_date', models.DateTimeField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event_duration', models.PositiveBigIntegerField()),
                ('venue', models.CharField(default=None, max_length=10)),
                ('organizer', models.CharField(default=None, max_length=10)),
                ('event_goal', models.CharField(default=None, max_length=10)),
                ('attendees', models.IntegerField()),
            ],
        ),
    ]
