# Generated by Django 3.2.4 on 2021-08-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_auto_20210813_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendars',
            name='event_goal',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='calendars',
            name='event_name',
            field=models.CharField(max_length=20),
        ),
    ]
