# Generated by Django 3.2.4 on 2021-09-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_auto_20210903_0533'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calendars',
            new_name='Event',
        ),
    ]
