# Generated by Django 3.2.4 on 2021-08-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='account_number',
            field=models.PositiveBigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='trainer',
            name='company',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='trainer',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='trainer',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='trainer',
            name='id_number',
            field=models.CharField(default=None, max_length=8),
        ),
        migrations.AddField(
            model_name='trainer',
            name='proffession',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='trainer',
            name='work_title',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='course_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
