# Generated by Django 3.2.4 on 2021-08-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_alter_trainer_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='account_number',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='company',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='course_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='id_number',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='proffession',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='work_title',
            field=models.CharField(max_length=10),
        ),
    ]
