# Generated by Django 3.2.4 on 2021-08-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_auto_20210813_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='company',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='id_number',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='proffession',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='work_title',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
