# Generated by Django 3.2.4 on 2021-08-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_auto_20210818_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='curriculum_vitae',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
