# Generated by Django 3.2.4 on 2021-08-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_auto_20210820_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainer_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
