# Generated by Django 3.2.4 on 2021-07-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_trainer', models.CharField(max_length=10)),
                ('course_code', models.CharField(max_length=5)),
            ],
        ),
    ]
