# Generated by Django 3.2.4 on 2021-08-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210812_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_description',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_trainer',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration_of_lesson',
            field=models.CharField(max_length=10),
        ),
    ]
