# Generated by Django 3.2.4 on 2021-08-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210813_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='notes',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
