# Generated by Django 3.2.4 on 2021-08-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210804_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='big_sister_name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
