# Generated by Django 3.2.4 on 2021-08-08 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_big_sister_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passport_photo',
        ),
    ]
