# Generated by Django 3.2.4 on 2021-08-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
