# Generated by Django 3.2.4 on 2021-08-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_passport_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
